### ISSUE TITLE
 Caused by: android.util.AndroidRuntimeException: Animators may only be run on Looper threads since Android O

### ISSUE THREAD

**Issue by fistons** [fistons/TinyTinyFeed#32]
Got this exception since Android O, prevent the widget to load

```
07-02 07:45:30.801 2248-2248/? W/AppWidgetHostView: updateAppWidget couldn't find any view, using error view
    android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class android.widget.ListView
    Caused by: android.view.InflateException: Binary XML file line #7: Error inflating class android.widget.ListView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.widget.RemoteViews.inflateView(RemoteViews.java:3498)
        at android.widget.RemoteViews.-wrap1(Unknown Source:0)
        at android.widget.RemoteViews$AsyncApplyTask.doInBackground(RemoteViews.java:3600)
        at android.widget.RemoteViews$AsyncApplyTask.doInBackground(RemoteViews.java:3596)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: android.util.AndroidRuntimeException: Animators may only be run on Looper threads
        at android.animation.AnimatorSet.start(AnimatorSet.java:705)
        at android.animation.AnimatorSet.start(AnimatorSet.java:684)
        at android.widget.FastScroller.transitionToHidden(FastScroller.java:876)
        at android.widget.FastScroller.setState(FastScroller.java:832)
        at android.widget.FastScroller.stop(FastScroller.java:474)
        at android.widget.FastScroller.onStateDependencyChanged(FastScroller.java:456)
        at android.widget.FastScroller.setEnabled(FastScroller.java:410)
        at android.widget.AbsListView.setFastScrollerEnabledUiThread(AbsListView.java:1290)
        at android.widget.AbsListView.setFastScrollEnabled(AbsListView.java:1273)
        at android.widget.AbsListView.<init>(AbsListView.java:856)
        at android.widget.ListView.<init>(ListView.java:227)
        at android.widget.ListView.<init>(ListView.java:223)
        at android.widget.ListView.<init>(ListView.java:219)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58) 
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:720) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:788) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.widget.RemoteViews.inflateView(RemoteViews.java:3498) 
        at android.widget.RemoteViews.-wrap1(Unknown Source:0) 
        at android.widget.RemoteViews$AsyncApplyTask.doInBackground(RemoteViews.java:3600) 
        at android.widget.RemoteViews$AsyncApplyTask.doInBackground(RemoteViews.java:3596) 
        at android.os.AsyncTask$2.call(AsyncTask.java:333) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 

```

**Comment by fistons** [comment]
Fixed with 074fccf79315ee0e
